let teams = [{
    groupid: 1,
    group: "A",
    clubs: [
      {
        id: 1,
        club: "FC Bayern Munich",
        location: "Munich, Germany",
        league: "Bundesliga",
        titles: "5",
        wonBefore: true,
        mostRecentWin: "2020",
        topScorer: "Robert Lewandowski",
        eliminated: false,
      },
      {
        id: 2, 
        club: "Atletico Madrid",
        location: "Madrid, Spain",
        league: "La Liga",
        titles: "0",
        topScorer: "Joao Felix",
        eliminated: false,
      },
      {
        id: 3, 
        club: "Red Bull Salzburg",
        location: "Salzburg, Austria",
        league: "Austrian Bundesliga",
        titles: "0",
        topScorer: "Zlatko Junuzovic",
        eliminated: true,
      },
      {
        id: 4, 
        club: "Lokomotiv Moscow",
        location: "Moscow, Russia",
        league: "Russian Premier League",
        titles: "0",
        topScorer: "Anton Miranchuk",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 2,
    group: "B",
    clubs: [
      {
        id: 5, 
        club: "Real Madrid",
        location: "Madrid, Spain",
        league: "La Liga",
        titles: "13",
        wonBefore: true,
        mostRecentWin: "2018",
        topScorer: "Karim Benzema",
        eliminated: false,
      },
      {
        id: 6, 
        club: "Borussia Monchengladbach",
        location: "Monchengladback, Germany",
        league: "Bundesliga",
        titles: "0",
        topScorer: "Alassane Plea",
        eliminated: false,
      },
      {
        id: 7, 
        club: "Shakhtar Donetsk",
        location: "Donetsk, Ukraine",
        league: "Ukranian Premier League",
        titles: "0",
        topScorer: "Manor Solomon",
        eliminated: true,
      },
      {
        id: 8, 
        club: "Inter Milan",
        location: "Milan, Italy",
        league: "Serie A",
        titles: "3",
        wonBefore: true,
        mostRecentWin: "2010",
        topScorer: "Romelu Lukaku",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 3,
    group: "C",
    clubs: [
      {
        id: 9, 
        club: "Manchester City",
        location: "Manchester, England",
        league: "Premier League",
        titles: "0",
        topScorer: "Ferran Torres",
        eliminated: false,
      },
      {
        id: 10, 
        club: "FC Porto",
        location: "Porto, Portugal",
        league: "Primeira Liga",
        titles: "2",
        wonBefore: true,
        mostRecentWin: "2004",
        topScorer: "Sergio Oliveira",
        eliminated: false,
      },
      {
        id: 11, 
        club: "Olympiacos",
        location: "Athens, Greece",
        league: "Super League Greece",
        titles: "0",
        topScorer: "Ahmed Hassan",
        eliminated: true,
      },
      {
        id: 12, 
        club: "Olympique de Marseille",
        location: "Marseille, France",
        league: "Ligue 1",
        titles: "1",
        wonBefore: true,
        mostRecentWin: "1993",
        topScorer: "Dimitri Payet",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 4,
    group: "D",
    clubs: [
      {
        id: 13, 
        club: "Liverpool FC",
        location: "Liverpool, England",
        league: "Permier League",
        titles: "6",
        wonBefore: true,
        mostRecentWin: "2019",
        topScorer: "Mohamed Salah",
        eliminated: false,
      },
      {
        id: 14, 
        club: "Atalanta",
        location: "Bergamo, Lombardy, Italy",
        league: "Serie A",
        titles: "0",
        topScorer: "Duvan Zapata",
        eliminated: false,
      },
      {
        id: 15, 
        club: "AFC Ajax",
        location: "Amsterdam, Netherlands",
        league: "Eredivisie",
        titles: "4",
        wonBefore: true,
        mostRecentWin: "1995",
        topScorer: "Dusan Tadic",
        eliminated: true,
      },
      {
        id: 16, 
        club: "Midtjylland",
        location: "Herning, Denmark",
        league: "Danish Superliga",
        titles: "0",
        topScorer: "Alexander Scholz",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 5,
    group: "E",
    clubs: [
      {
        id: 17, 
        club: "Chelsea FC",
        location: "London, England",
        league: "Permier League",
        titles: "1",
        wonBefore: true,
        mostRecentWin: "2012",
        topScorer: "Olivier Giroud",
        eliminated: false,
      },
      {
        id: 18, 
        club: "Sevilla",
        location: "Seville, Spain",
        league: "La Liga",
        titles: "0",
        topScorer: "Youssef En-Nesyri",
        eliminated: false,
      },
      {
        id: 19, 
        club: "FC Krasnodar",
        location: "Krasnodar, Russia",
        league: "Russian Premier League",
        titles: "0",
        topScorer: "Marcus Berg",
        eliminated: true,
      },
      {
        id: 20, 
        club: "Stade Rennais FC",
        location: "Rennes, France",
        league: "Ligue 1",
        titles: "0",
        topScorer: "Sehrou Guirassy",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 6,
    group: "F",
    clubs: [
      {
        id: 21, 
        club: "Borussia Dortmund",
        location: "Dortmund, Germany",
        league: "Bundesliga",
        titles: "1",
        wonBefore: true,
        mostRecentWin: "1997",
        topScorer: "Erling Haaland",
        eliminated: false,
      },
      {
        id: 22, 
        club: "SS Lazio",
        location: "Rome, Italy",
        league: "Serie A",
        titles: "0",
        topScorer: "Ciro Immobile",
        eliminated: false,
      },
      {
        id: 23, 
        club: "Club Brugge KV",
        location: "Bruges, Belgium",
        league: "Belgian First Division A",
        titles: "0",
        topScorer: "Hans Vanaken",
        eliminated: true,
      },
      {
        id: 24, 
        club: "FC Zenit St. Petersburg",
        location: "St. Petersburg, Russia",
        league: "Russian Premier League",
        titles: "0",
        topScorer: "Artem Dzyuba",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 7,
    group: "G",
    clubs: [
      {
        id: 25, 
        club: "Juventus FC",
        location: "Turin, Italy",
        league: "Serie A",
        titles: "2",
        wonBefore: true,
        mostRecentWin: "1996",
        topScorer: "Alvaro Morata",
        eliminated: false,
      },
      {
        id: 26, 
        club: "FC Barcelona",
        location: "Barcelona, Spain",
        league: "La Liga",
        titles: "5",
        wonBefore: true,
        mostRecentWin: "2015",
        topScorer: "Lionel Messi",
        eliminated: false,
      },
      {
        id: 27, 
        club: "FC Dynamo Kyiv",
        location: "Kyiv, Ukraine",
        league: "Ukranian Premier League",
        titles: "0",
        topScorer: "Viktor Tsygankov",
        eliminated: true,
      },
      {
        id: 28, 
        club: "Ferencvarosi TC",
        location: "Ferencvaros, Hungary",
        league: "NB I",
        titles: "0",
        topScorer: "Franck Boli",
        eliminated: true,
      },
    ]
  },
  {
    groupid: 8,
    group: "H",
    clubs: [
      {
        id: 29, 
        club: "Paris Saint-Germain FC",
        group: "H",
        location: "Paris, France",
        league: "Ligue 1",
        titles: "0",
        topScorer: "Kylian Mbappe",
        eliminated: false,
      },
      {
        id: 30, 
        club: "RB Leipzig",
        group: "H",
        location: "Leipzig, Germany",
        league: "Bundesliga",
        titles: "0",
        topScorer: "Angelino",
        eliminated: false,
      },
      {
        id: 31, 
        club: "Manchester United",
        group: "H",
        location: "Manchester, England",
        league: "Premier League",
        titles: "3",
        wonBefore: true,
        mostRecentWin: "2008",
        topScorer: "Marcus Rashford",
        eliminated: true,
      },
      {
        id: 32, 
        club: "Istanbul Basaksehir",
        group: "H",
        location: "Istanbul, Turkey",
        league: "Super Lig",
        titles: "0",
        topScorer: "Irfan Can Kahveci",
        eliminated: true,
      },
    ]
  },
]

export default teams;
